heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls: ["http://es-pract8:9200"]
  check.request:
    method: "GET"
  check.response:
    status: 200
output.elasticsearch:
  hosts: ["es-pract8:9200"]
