version: '3'
services:
  es-pract3:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: es-pract3
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
volumes:
  esdata1:
    driver: local
