version: '3'
services:
  es-pract9:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: es-pract9
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es-data9:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
  logstash-pract9:
    user: root
    image: docker.elastic.co/logstash/logstash-oss:6.4.3
    container_name: logstash-pract9
    volumes:
      - ./pipeline:/usr/share/logstash/pipeline/
  filebeat-pract9:
    user: root
    image: docker.elastic.co/beats/filebeat:6.4.2
    container_name: filebeat-pract9
    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./data/:/var/log/pratc9/
  kibana-pract9:
    image: docker.elastic.co/kibana/kibana:6.4.2
    environment:
     ELASTICSEARCH_URL: http://es-pract9:9200
    ports:
      - 5601:5601
volumes:
  es-data9:
    driver: local


